#!/bin/bash
# This script was generated by scangen
# To be run as: singularity exec --cleanenv --bind .:/scratch/runarea/my_scan,$SCANGEN_ROOT:/scratch/programs/scangen$SCANGEN_ROOT/singularity/heptools.sif bash /scratch/runarea/my_scan/start-runs.sh

root_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $root_dir/runarea/runscripts
cd 13TeV
bash run-jobs.sh
cd ..
